import { Action, AppState, ModeConfig, Mode, Reward } from "./types";

export const MODES: Record<Mode, ModeConfig> = {
  easy: { earnMul: 1.5, spendMul: 0.7, label: "イージーモード", emoji: "🟢" },
  normal: {
    earnMul: 1.0,
    spendMul: 1.0,
    label: "ノーマルモード",
    emoji: "🟡",
  },
  hard: { earnMul: 0.8, spendMul: 1.5, label: "ハードモード", emoji: "🔴" },
};

export const DEFAULT_ACTIONS: Action[] = [
  {
    id: 1,
    title: "朝ごはんを食べる",
    desc: "",
    tags: ["食事", "朝"],
    hurdle: 1,
    time: 1,
  },
  {
    id: 2,
    title: "風呂に入る",
    desc: "シャワーでもOK",
    tags: ["衛生", "セルフケア"],
    hurdle: 2,
    time: 2,
  },
  {
    id: 3,
    title: "食器を片付ける",
    desc: "",
    tags: ["家事", "キッチン"],
    hurdle: 1,
    time: 1,
  },
  {
    id: 4,
    title: "部屋を掃除する",
    desc: "",
    tags: ["家事", "掃除"],
    hurdle: 3,
    time: 3,
  },
  {
    id: 5,
    title: "洗濯する",
    desc: "",
    tags: ["家事"],
    hurdle: 2,
    time: 2,
  },
  {
    id: 6,
    title: "洗濯物をたたむ",
    desc: "",
    tags: ["家事"],
    hurdle: 2,
    time: 2,
  },
  {
    id: 7,
    title: "ゴミを捨てる",
    desc: "",
    tags: ["家事", "掃除"],
    hurdle: 1,
    time: 1,
  },
  {
    id: 8,
    title: "トイレを掃除する",
    desc: "",
    tags: ["家事", "掃除"],
    hurdle: 3,
    time: 2,
  },
  {
    id: 9,
    title: "歯磨きをする",
    desc: "",
    tags: ["衛生", "朝", "夜"],
    hurdle: 1,
    time: 1,
  },
  {
    id: 10,
    title: "顔を洗う",
    desc: "",
    tags: ["衛生", "朝"],
    hurdle: 1,
    time: 1,
  },
  {
    id: 11,
    title: "水を飲む",
    desc: "200ml以上",
    tags: ["健康", "セルフケア"],
    hurdle: 1,
    time: 1,
  },
  {
    id: 12,
    title: "ストレッチをする",
    desc: "5分以上",
    tags: ["運動", "健康"],
    hurdle: 1,
    time: 1,
  },
  {
    id: 13,
    title: "散歩に行く",
    desc: "15分以上",
    tags: ["運動", "外出"],
    hurdle: 2,
    time: 2,
  },
  {
    id: 14,
    title: "ジョギングする",
    desc: "",
    tags: ["運動", "外出"],
    hurdle: 3,
    time: 3,
  },
  {
    id: 15,
    title: "筋トレをする",
    desc: "",
    tags: ["運動", "健康"],
    hurdle: 3,
    time: 2,
  },
  {
    id: 16,
    title: "昼ごはんを食べる",
    desc: "",
    tags: ["食事"],
    hurdle: 1,
    time: 1,
  },
  {
    id: 17,
    title: "夜ごはんを食べる",
    desc: "",
    tags: ["食事", "夜"],
    hurdle: 1,
    time: 1,
  },
  {
    id: 18,
    title: "薬を飲む",
    desc: "",
    tags: ["健康", "セルフケア"],
    hurdle: 1,
    time: 1,
  },
  {
    id: 19,
    title: "メールを返信する",
    desc: "",
    tags: ["仕事", "タスク"],
    hurdle: 2,
    time: 2,
  },
  {
    id: 20,
    title: "タスクリストを整理する",
    desc: "",
    tags: ["仕事", "タスク"],
    hurdle: 2,
    time: 2,
  },
  {
    id: 21,
    title: "読書をする",
    desc: "10ページ以上",
    tags: ["学習", "自己投資"],
    hurdle: 2,
    time: 2,
  },
  {
    id: 22,
    title: "日記を書く",
    desc: "",
    tags: ["メンタル", "振り返り"],
    hurdle: 2,
    time: 1,
  },
  {
    id: 23,
    title: "勉強する",
    desc: "30分以上",
    tags: ["学習", "自己投資"],
    hurdle: 3,
    time: 3,
  },
  {
    id: 24,
    title: "シンクを磨く",
    desc: "",
    tags: ["家事", "キッチン", "掃除"],
    hurdle: 2,
    time: 1,
  },
  {
    id: 25,
    title: "窓を拭く",
    desc: "",
    tags: ["家事", "掃除"],
    hurdle: 2,
    time: 2,
  },
  {
    id: 26,
    title: "冷蔵庫を整理する",
    desc: "",
    tags: ["家事", "キッチン"],
    hurdle: 2,
    time: 2,
  },
  {
    id: 27,
    title: "買い物リストを作る",
    desc: "",
    tags: ["タスク", "準備"],
    hurdle: 1,
    time: 1,
  },
  {
    id: 28,
    title: "買い物に行く",
    desc: "",
    tags: ["外出", "タスク"],
    hurdle: 2,
    time: 3,
  },
  {
    id: 29,
    title: "布団を干す",
    desc: "",
    tags: ["家事"],
    hurdle: 2,
    time: 1,
  },
  {
    id: 30,
    title: "早起きする",
    desc: "7時前に起床",
    tags: ["習慣", "朝"],
    hurdle: 3,
    time: 1,
  },
  {
    id: 31,
    title: "定時に寝る",
    desc: "24時前",
    tags: ["習慣", "夜", "健康"],
    hurdle: 3,
    time: 1,
  },
  {
    id: 32,
    title: "SNSを30分以内にする",
    desc: "",
    tags: ["習慣", "メンタル"],
    hurdle: 3,
    time: 1,
  },
  {
    id: 33,
    title: "机を片付ける",
    desc: "",
    tags: ["家事", "掃除"],
    hurdle: 2,
    time: 1,
  },
  {
    id: 34,
    title: "プログラミングの勉強",
    desc: "",
    tags: ["学習", "仕事", "自己投資"],
    hurdle: 3,
    time: 4,
  },
  {
    id: 35,
    title: "英語の勉強",
    desc: "単語10個",
    tags: ["学習", "自己投資"],
    hurdle: 2,
    time: 1,
  },
  {
    id: 36,
    title: "瞑想する",
    desc: "5分",
    tags: ["メンタル", "セルフケア"],
    hurdle: 2,
    time: 1,
  },
  {
    id: 37,
    title: "深呼吸する",
    desc: "10回",
    tags: ["メンタル", "セルフケア"],
    hurdle: 1,
    time: 1,
  },
  {
    id: 38,
    title: "友達に連絡する",
    desc: "",
    tags: ["人間関係"],
    hurdle: 2,
    time: 1,
  },
  {
    id: 39,
    title: "家計簿をつける",
    desc: "",
    tags: ["お金", "タスク"],
    hurdle: 2,
    time: 1,
  },
  {
    id: 40,
    title: "請求書を確認する",
    desc: "",
    tags: ["お金", "タスク"],
    hurdle: 2,
    time: 1,
  },
  {
    id: 41,
    title: "お風呂の掃除",
    desc: "",
    tags: ["家事", "掃除"],
    hurdle: 3,
    time: 2,
  },
  {
    id: 42,
    title: "洗面台を掃除する",
    desc: "",
    tags: ["家事", "掃除", "衛生"],
    hurdle: 2,
    time: 1,
  },
  {
    id: 43,
    title: "ベッドメイキング",
    desc: "",
    tags: ["家事", "朝"],
    hurdle: 1,
    time: 1,
  },
  {
    id: 44,
    title: "靴を磨く",
    desc: "",
    tags: ["衛生", "準備"],
    hurdle: 2,
    time: 1,
  },
  {
    id: 45,
    title: "爪を切る",
    desc: "",
    tags: ["衛生", "セルフケア"],
    hurdle: 1,
    time: 1,
  },
  {
    id: 46,
    title: "植物に水をやる",
    desc: "",
    tags: ["家事"],
    hurdle: 1,
    time: 1,
  },
  {
    id: 47,
    title: "5分だけ作業を始める",
    desc: "とにかく始める",
    tags: ["習慣", "タスク"],
    hurdle: 2,
    time: 1,
  },
  {
    id: 48,
    title: "クローゼットを整理する",
    desc: "",
    tags: ["家事", "掃除"],
    hurdle: 3,
    time: 3,
  },
  {
    id: 49,
    title: "スマホを別の部屋に置く",
    desc: "1時間",
    tags: ["習慣", "メンタル"],
    hurdle: 3,
    time: 3,
  },
  {
    id: 50,
    title: "今日の振り返りをする",
    desc: "",
    tags: ["振り返り", "夜", "メンタル"],
    hurdle: 2,
    time: 1,
  },
];

export const DEFAULT_REWARDS: Reward[] = [
  {
    id: 51,
    title: "YouTube動画を見る",
    desc: "30分まで",
    tags: ["動画", "スマホ"],
    satisfaction: 2,
    time: 2,
    price: 1,
  },
  {
    id: 52,
    title: "ゲームをする",
    desc: "",
    tags: ["ゲーム"],
    satisfaction: 3,
    time: 3,
    price: 1,
  },
  {
    id: 53,
    title: "コンビニスイーツ",
    desc: "",
    tags: ["食べ物", "お出かけ"],
    satisfaction: 2,
    time: 1,
    price: 2,
  },
  {
    id: 54,
    title: "Netflix を1話見る",
    desc: "",
    tags: ["動画", "映像"],
    satisfaction: 2,
    time: 3,
    price: 1,
  },
  {
    id: 55,
    title: "昼寝をする",
    desc: "30分",
    tags: ["休息"],
    satisfaction: 2,
    time: 2,
    price: 1,
  },
  {
    id: 56,
    title: "お気に入りの音楽を聴く",
    desc: "",
    tags: ["音楽", "休息"],
    satisfaction: 1,
    time: 2,
    price: 1,
  },
  {
    id: 57,
    title: "カフェに行く",
    desc: "",
    tags: ["お出かけ", "まったり"],
    satisfaction: 2,
    time: 3,
    price: 2,
  },
  {
    id: 58,
    title: "マンガを読む",
    desc: "1巻",
    tags: ["読み物", "まったり"],
    satisfaction: 2,
    time: 2,
    price: 2,
  },
  {
    id: 59,
    title: "お菓子を食べる",
    desc: "",
    tags: ["食べ物"],
    satisfaction: 1,
    time: 1,
    price: 1,
  },
  {
    id: 60,
    title: "SNSをだらだら見る",
    desc: "30分",
    tags: ["スマホ"],
    satisfaction: 1,
    time: 2,
    price: 1,
  },
  {
    id: 61,
    title: "ゆっくりお風呂に入る",
    desc: "湯船に浸かる",
    tags: ["休息", "セルフケア"],
    satisfaction: 3,
    time: 2,
    price: 1,
  },
  {
    id: 62,
    title: "好きな映画を見る",
    desc: "",
    tags: ["動画", "映像", "まったり"],
    satisfaction: 3,
    time: 4,
    price: 1,
  },
  {
    id: 63,
    title: "ドライブに行く",
    desc: "",
    tags: ["お出かけ", "外出"],
    satisfaction: 3,
    time: 4,
    price: 3,
  },
  {
    id: 64,
    title: "外食する",
    desc: "",
    tags: ["食べ物", "お出かけ"],
    satisfaction: 3,
    time: 3,
    price: 3,
  },
  {
    id: 65,
    title: "コンビニに寄る",
    desc: "好きなもの1つ",
    tags: ["食べ物", "お出かけ"],
    satisfaction: 1,
    time: 1,
    price: 1,
  },
  {
    id: 66,
    title: "本を買う",
    desc: "",
    tags: ["買い物", "読み物"],
    satisfaction: 2,
    time: 1,
    price: 2,
  },
  {
    id: 67,
    title: "ゲームを1時間する",
    desc: "",
    tags: ["ゲーム"],
    satisfaction: 3,
    time: 4,
    price: 1,
  },
  {
    id: 68,
    title: "スマホゲームをする",
    desc: "15分",
    tags: ["ゲーム", "スマホ"],
    satisfaction: 1,
    time: 1,
    price: 1,
  },
  {
    id: 69,
    title: "アニメを1話見る",
    desc: "",
    tags: ["動画", "映像"],
    satisfaction: 2,
    time: 2,
    price: 1,
  },
  {
    id: 70,
    title: "Twitterを見る",
    desc: "15分",
    tags: ["スマホ"],
    satisfaction: 1,
    time: 1,
    price: 1,
  },
  {
    id: 71,
    title: "好きなポッドキャストを聴く",
    desc: "",
    tags: ["音楽", "学習"],
    satisfaction: 2,
    time: 3,
    price: 1,
  },
  {
    id: 72,
    title: "温泉・銭湯に行く",
    desc: "",
    tags: ["お出かけ", "セルフケア"],
    satisfaction: 3,
    time: 4,
    price: 2,
  },
  {
    id: 73,
    title: "ショッピングに行く",
    desc: "",
    tags: ["買い物", "お出かけ"],
    satisfaction: 3,
    time: 4,
    price: 4,
  },
  {
    id: 74,
    title: "ランチを奮発する",
    desc: "",
    tags: ["食べ物", "お出かけ"],
    satisfaction: 2,
    time: 2,
    price: 3,
  },
  {
    id: 75,
    title: "デザートを食べる",
    desc: "",
    tags: ["食べ物"],
    satisfaction: 2,
    time: 1,
    price: 2,
  },
  {
    id: 76,
    title: "好きなゲームを買う",
    desc: "",
    tags: ["ゲーム", "買い物"],
    satisfaction: 3,
    time: 1,
    price: 4,
  },
  {
    id: 77,
    title: "オンラインショッピング",
    desc: "1000円以内",
    tags: ["買い物"],
    satisfaction: 2,
    time: 2,
    price: 2,
  },
  {
    id: 78,
    title: "友達と遊ぶ",
    desc: "",
    tags: ["人間関係", "お出かけ"],
    satisfaction: 3,
    time: 5,
    price: 3,
  },
  {
    id: 79,
    title: "ゆっくり読書する",
    desc: "好きな本",
    tags: ["読み物", "まったり"],
    satisfaction: 2,
    time: 3,
    price: 1,
  },
  {
    id: 80,
    title: "お気に入りのカフェでPC作業",
    desc: "",
    tags: ["お出かけ", "まったり"],
    satisfaction: 2,
    time: 4,
    price: 2,
  },
  {
    id: 81,
    title: "公園でぼーっとする",
    desc: "",
    tags: ["外出", "休息"],
    satisfaction: 2,
    time: 2,
    price: 1,
  },
  {
    id: 82,
    title: "好きなYouTuberを見る",
    desc: "1本",
    tags: ["動画", "スマホ"],
    satisfaction: 2,
    time: 2,
    price: 1,
  },
  {
    id: 83,
    title: "ゲーム実況を見る",
    desc: "",
    tags: ["動画", "ゲーム"],
    satisfaction: 1,
    time: 2,
    price: 1,
  },
  {
    id: 84,
    title: "好きなアーティストの曲を聴く",
    desc: "アルバム1枚",
    tags: ["音楽"],
    satisfaction: 2,
    time: 3,
    price: 1,
  },
  {
    id: 85,
    title: "カラオケに行く",
    desc: "",
    tags: ["音楽", "お出かけ"],
    satisfaction: 3,
    time: 4,
    price: 3,
  },
  {
    id: 86,
    title: "ボードゲームをする",
    desc: "",
    tags: ["ゲーム", "人間関係"],
    satisfaction: 3,
    time: 4,
    price: 2,
  },
  {
    id: 87,
    title: "マッサージを受ける",
    desc: "",
    tags: ["セルフケア", "お出かけ"],
    satisfaction: 3,
    time: 3,
    price: 4,
  },
  {
    id: 88,
    title: "好きな服を買う",
    desc: "",
    tags: ["買い物", "お出かけ"],
    satisfaction: 3,
    time: 3,
    price: 5,
  },
  {
    id: 89,
    title: "ゲームの課金",
    desc: "500円分",
    tags: ["ゲーム", "買い物"],
    satisfaction: 2,
    time: 1,
    price: 2,
  },
  {
    id: 90,
    title: "タピオカを飲む",
    desc: "",
    tags: ["食べ物", "お出かけ"],
    satisfaction: 1,
    time: 1,
    price: 2,
  },
  {
    id: 91,
    title: "スイーツ巡りをする",
    desc: "",
    tags: ["食べ物", "お出かけ"],
    satisfaction: 3,
    time: 4,
    price: 3,
  },
  {
    id: 92,
    title: "旅行の計画を立てる",
    desc: "",
    tags: ["まったり", "準備"],
    satisfaction: 2,
    time: 3,
    price: 1,
  },
  {
    id: 93,
    title: "日帰り旅行",
    desc: "",
    tags: ["お出かけ", "外出"],
    satisfaction: 3,
    time: 6,
    price: 4,
  },
  {
    id: 94,
    title: "好きな動画を倍速なしで見る",
    desc: "",
    tags: ["動画", "まったり"],
    satisfaction: 2,
    time: 3,
    price: 1,
  },
  {
    id: 95,
    title: "ゆっくり料理する",
    desc: "好きなもの",
    tags: ["食べ物", "まったり"],
    satisfaction: 2,
    time: 3,
    price: 2,
  },
  {
    id: 96,
    title: "パフェを食べる",
    desc: "",
    tags: ["食べ物", "お出かけ"],
    satisfaction: 3,
    time: 1,
    price: 2,
  },
  {
    id: 97,
    title: "ゲームを思う存分する",
    desc: "3時間",
    tags: ["ゲーム"],
    satisfaction: 3,
    time: 5,
    price: 1,
  },
  {
    id: 98,
    title: "サウナに行く",
    desc: "",
    tags: ["セルフケア", "お出かけ"],
    satisfaction: 3,
    time: 3,
    price: 3,
  },
  {
    id: 99,
    title: "ネットサーフィンする",
    desc: "30分",
    tags: ["スマホ", "まったり"],
    satisfaction: 1,
    time: 2,
    price: 1,
  },
  {
    id: 100,
    title: "好きな人と電話する",
    desc: "",
    tags: ["人間関係"],
    satisfaction: 3,
    time: 3,
    price: 1,
  },
];

export const INITIAL_STATE: AppState = {
  points: 0,
  mode: "normal",
  actions: [],
  rewards: [],
  doneActions: [],
  doneRewards: [],
};

export const STORAGE_KEY = "tekipakky_state";
