import { PrismaClient } from "../lib/generated/prisma/client";
import { PrismaPg } from "@prisma/adapter-pg";

const adapter = new PrismaPg({ connectionString: process.env.DATABASE_URL! });
const prisma = new PrismaClient({ adapter });

const DEFAULT_ACTIONS = [
  {
    title: "朝ごはんを食べる",
    desc: "",
    tags: ["食事", "朝"],
    hurdle: 1,
    time: 1,
  },
  {
    title: "風呂に入る",
    desc: "シャワーでもOK",
    tags: ["衛生", "セルフケア"],
    hurdle: 2,
    time: 2,
  },
  {
    title: "食器を片付ける",
    desc: "",
    tags: ["家事", "キッチン"],
    hurdle: 1,
    time: 1,
  },
  {
    title: "部屋を掃除する",
    desc: "",
    tags: ["家事", "掃除"],
    hurdle: 3,
    time: 3,
  },
  { title: "洗濯する", desc: "", tags: ["家事"], hurdle: 2, time: 2 },
  { title: "洗濯物をたたむ", desc: "", tags: ["家事"], hurdle: 2, time: 2 },
  {
    title: "ゴミを捨てる",
    desc: "",
    tags: ["家事", "掃除"],
    hurdle: 1,
    time: 1,
  },
  {
    title: "トイレを掃除する",
    desc: "",
    tags: ["家事", "掃除"],
    hurdle: 3,
    time: 2,
  },
  {
    title: "歯磨きをする",
    desc: "",
    tags: ["衛生", "朝", "夜"],
    hurdle: 1,
    time: 1,
  },
  { title: "顔を洗う", desc: "", tags: ["衛生", "朝"], hurdle: 1, time: 1 },
  {
    title: "水を飲む",
    desc: "200ml以上",
    tags: ["健康", "セルフケア"],
    hurdle: 1,
    time: 1,
  },
  {
    title: "ストレッチをする",
    desc: "5分以上",
    tags: ["運動", "健康"],
    hurdle: 1,
    time: 1,
  },
  {
    title: "散歩に行く",
    desc: "15分以上",
    tags: ["運動", "外出"],
    hurdle: 2,
    time: 2,
  },
  {
    title: "ジョギングする",
    desc: "",
    tags: ["運動", "外出"],
    hurdle: 3,
    time: 3,
  },
  {
    title: "筋トレをする",
    desc: "",
    tags: ["運動", "健康"],
    hurdle: 3,
    time: 2,
  },
  { title: "昼ごはんを食べる", desc: "", tags: ["食事"], hurdle: 1, time: 1 },
  {
    title: "夜ごはんを食べる",
    desc: "",
    tags: ["食事", "夜"],
    hurdle: 1,
    time: 1,
  },
  {
    title: "薬を飲む",
    desc: "",
    tags: ["健康", "セルフケア"],
    hurdle: 1,
    time: 1,
  },
  {
    title: "メールを返信する",
    desc: "",
    tags: ["仕事", "タスク"],
    hurdle: 2,
    time: 2,
  },
  {
    title: "タスクリストを整理する",
    desc: "",
    tags: ["仕事", "タスク"],
    hurdle: 2,
    time: 2,
  },
  {
    title: "読書をする",
    desc: "10ページ以上",
    tags: ["学習", "自己投資"],
    hurdle: 2,
    time: 2,
  },
  {
    title: "日記を書く",
    desc: "",
    tags: ["メンタル", "振り返り"],
    hurdle: 2,
    time: 1,
  },
  {
    title: "勉強する",
    desc: "30分以上",
    tags: ["学習", "自己投資"],
    hurdle: 3,
    time: 3,
  },
  {
    title: "シンクを磨く",
    desc: "",
    tags: ["家事", "キッチン", "掃除"],
    hurdle: 2,
    time: 1,
  },
  { title: "窓を拭く", desc: "", tags: ["家事", "掃除"], hurdle: 2, time: 2 },
  {
    title: "冷蔵庫を整理する",
    desc: "",
    tags: ["家事", "キッチン"],
    hurdle: 2,
    time: 2,
  },
  {
    title: "買い物リストを作る",
    desc: "",
    tags: ["タスク", "準備"],
    hurdle: 1,
    time: 1,
  },
  {
    title: "買い物に行く",
    desc: "",
    tags: ["外出", "タスク"],
    hurdle: 2,
    time: 3,
  },
  { title: "布団を干す", desc: "", tags: ["家事"], hurdle: 2, time: 1 },
  {
    title: "早起きする",
    desc: "7時前に起床",
    tags: ["習慣", "朝"],
    hurdle: 3,
    time: 1,
  },
  {
    title: "定時に寝る",
    desc: "24時前",
    tags: ["習慣", "夜", "健康"],
    hurdle: 3,
    time: 1,
  },
  {
    title: "SNSを30分以内にする",
    desc: "",
    tags: ["習慣", "メンタル"],
    hurdle: 3,
    time: 1,
  },
  {
    title: "机を片付ける",
    desc: "",
    tags: ["家事", "掃除"],
    hurdle: 2,
    time: 1,
  },
  {
    title: "プログラミングの勉強",
    desc: "",
    tags: ["学習", "仕事", "自己投資"],
    hurdle: 3,
    time: 4,
  },
  {
    title: "英語の勉強",
    desc: "単語10個",
    tags: ["学習", "自己投資"],
    hurdle: 2,
    time: 1,
  },
  {
    title: "瞑想する",
    desc: "5分",
    tags: ["メンタル", "セルフケア"],
    hurdle: 2,
    time: 1,
  },
  {
    title: "深呼吸する",
    desc: "10回",
    tags: ["メンタル", "セルフケア"],
    hurdle: 1,
    time: 1,
  },
  { title: "友達に連絡する", desc: "", tags: ["人間関係"], hurdle: 2, time: 1 },
  {
    title: "家計簿をつける",
    desc: "",
    tags: ["お金", "タスク"],
    hurdle: 2,
    time: 1,
  },
  {
    title: "請求書を確認する",
    desc: "",
    tags: ["お金", "タスク"],
    hurdle: 2,
    time: 1,
  },
  {
    title: "お風呂の掃除",
    desc: "",
    tags: ["家事", "掃除"],
    hurdle: 3,
    time: 2,
  },
  {
    title: "洗面台を掃除する",
    desc: "",
    tags: ["家事", "掃除", "衛生"],
    hurdle: 2,
    time: 1,
  },
  {
    title: "ベッドメイキング",
    desc: "",
    tags: ["家事", "朝"],
    hurdle: 1,
    time: 1,
  },
  { title: "靴を磨く", desc: "", tags: ["衛生", "準備"], hurdle: 2, time: 1 },
  {
    title: "爪を切る",
    desc: "",
    tags: ["衛生", "セルフケア"],
    hurdle: 1,
    time: 1,
  },
  { title: "植物に水をやる", desc: "", tags: ["家事"], hurdle: 1, time: 1 },
  {
    title: "5分だけ作業を始める",
    desc: "とにかく始める",
    tags: ["習慣", "タスク"],
    hurdle: 2,
    time: 1,
  },
  {
    title: "クローゼットを整理する",
    desc: "",
    tags: ["家事", "掃除"],
    hurdle: 3,
    time: 3,
  },
  {
    title: "スマホを別の部屋に置く",
    desc: "1時間",
    tags: ["習慣", "メンタル"],
    hurdle: 3,
    time: 3,
  },
  {
    title: "今日の振り返りをする",
    desc: "",
    tags: ["振り返り", "夜", "メンタル"],
    hurdle: 2,
    time: 1,
  },
];

const DEFAULT_REWARDS = [
  {
    title: "YouTube動画を見る",
    desc: "30分まで",
    tags: ["動画", "スマホ"],
    satisfaction: 2,
    time: 2,
    price: 1,
  },
  {
    title: "ゲームをする",
    desc: "",
    tags: ["ゲーム"],
    satisfaction: 3,
    time: 3,
    price: 1,
  },
  {
    title: "コンビニスイーツ",
    desc: "",
    tags: ["食べ物", "お出かけ"],
    satisfaction: 2,
    time: 1,
    price: 2,
  },
  {
    title: "Netflix を1話見る",
    desc: "",
    tags: ["動画", "映像"],
    satisfaction: 2,
    time: 3,
    price: 1,
  },
  {
    title: "昼寝をする",
    desc: "30分",
    tags: ["休息"],
    satisfaction: 2,
    time: 2,
    price: 1,
  },
  {
    title: "お気に入りの音楽を聴く",
    desc: "",
    tags: ["音楽", "休息"],
    satisfaction: 1,
    time: 2,
    price: 1,
  },
  {
    title: "カフェに行く",
    desc: "",
    tags: ["お出かけ", "まったり"],
    satisfaction: 2,
    time: 3,
    price: 2,
  },
  {
    title: "マンガを読む",
    desc: "1巻",
    tags: ["読み物", "まったり"],
    satisfaction: 2,
    time: 2,
    price: 2,
  },
  {
    title: "お菓子を食べる",
    desc: "",
    tags: ["食べ物"],
    satisfaction: 1,
    time: 1,
    price: 1,
  },
  {
    title: "SNSをだらだら見る",
    desc: "30分",
    tags: ["スマホ"],
    satisfaction: 1,
    time: 2,
    price: 1,
  },
  {
    title: "ゆっくりお風呂に入る",
    desc: "湯船に浸かる",
    tags: ["休息", "セルフケア"],
    satisfaction: 3,
    time: 2,
    price: 1,
  },
  {
    title: "好きな映画を見る",
    desc: "",
    tags: ["動画", "映像", "まったり"],
    satisfaction: 3,
    time: 4,
    price: 1,
  },
  {
    title: "ドライブに行く",
    desc: "",
    tags: ["お出かけ", "外出"],
    satisfaction: 3,
    time: 4,
    price: 3,
  },
  {
    title: "外食する",
    desc: "",
    tags: ["食べ物", "お出かけ"],
    satisfaction: 3,
    time: 3,
    price: 3,
  },
  {
    title: "コンビニに寄る",
    desc: "好きなもの1つ",
    tags: ["食べ物", "お出かけ"],
    satisfaction: 1,
    time: 1,
    price: 1,
  },
  {
    title: "本を買う",
    desc: "",
    tags: ["買い物", "読み物"],
    satisfaction: 2,
    time: 1,
    price: 2,
  },
  {
    title: "ゲームを1時間する",
    desc: "",
    tags: ["ゲーム"],
    satisfaction: 3,
    time: 4,
    price: 1,
  },
  {
    title: "スマホゲームをする",
    desc: "15分",
    tags: ["ゲーム", "スマホ"],
    satisfaction: 1,
    time: 1,
    price: 1,
  },
  {
    title: "アニメを1話見る",
    desc: "",
    tags: ["動画", "映像"],
    satisfaction: 2,
    time: 2,
    price: 1,
  },
  {
    title: "Twitterを見る",
    desc: "15分",
    tags: ["スマホ"],
    satisfaction: 1,
    time: 1,
    price: 1,
  },
  {
    title: "好きなポッドキャストを聴く",
    desc: "",
    tags: ["音楽", "学習"],
    satisfaction: 2,
    time: 3,
    price: 1,
  },
  {
    title: "温泉・銭湯に行く",
    desc: "",
    tags: ["お出かけ", "セルフケア"],
    satisfaction: 3,
    time: 4,
    price: 2,
  },
  {
    title: "ショッピングに行く",
    desc: "",
    tags: ["買い物", "お出かけ"],
    satisfaction: 3,
    time: 4,
    price: 4,
  },
  {
    title: "ランチを奮発する",
    desc: "",
    tags: ["食べ物", "お出かけ"],
    satisfaction: 2,
    time: 2,
    price: 3,
  },
  {
    title: "デザートを食べる",
    desc: "",
    tags: ["食べ物"],
    satisfaction: 2,
    time: 1,
    price: 2,
  },
  {
    title: "好きなゲームを買う",
    desc: "",
    tags: ["ゲーム", "買い物"],
    satisfaction: 3,
    time: 1,
    price: 4,
  },
  {
    title: "オンラインショッピング",
    desc: "1000円以内",
    tags: ["買い物"],
    satisfaction: 2,
    time: 2,
    price: 2,
  },
  {
    title: "友達と遊ぶ",
    desc: "",
    tags: ["人間関係", "お出かけ"],
    satisfaction: 3,
    time: 5,
    price: 3,
  },
  {
    title: "ゆっくり読書する",
    desc: "好きな本",
    tags: ["読み物", "まったり"],
    satisfaction: 2,
    time: 3,
    price: 1,
  },
  {
    title: "お気に入りのカフェでPC作業",
    desc: "",
    tags: ["お出かけ", "まったり"],
    satisfaction: 2,
    time: 4,
    price: 2,
  },
  {
    title: "公園でぼーっとする",
    desc: "",
    tags: ["外出", "休息"],
    satisfaction: 2,
    time: 2,
    price: 1,
  },
  {
    title: "好きなYouTuberを見る",
    desc: "1本",
    tags: ["動画", "スマホ"],
    satisfaction: 2,
    time: 2,
    price: 1,
  },
  {
    title: "ゲーム実況を見る",
    desc: "",
    tags: ["動画", "ゲーム"],
    satisfaction: 1,
    time: 2,
    price: 1,
  },
  {
    title: "好きなアーティストの曲を聴く",
    desc: "アルバム1枚",
    tags: ["音楽"],
    satisfaction: 2,
    time: 3,
    price: 1,
  },
  {
    title: "カラオケに行く",
    desc: "",
    tags: ["音楽", "お出かけ"],
    satisfaction: 3,
    time: 4,
    price: 3,
  },
  {
    title: "ボードゲームをする",
    desc: "",
    tags: ["ゲーム", "人間関係"],
    satisfaction: 3,
    time: 4,
    price: 2,
  },
  {
    title: "マッサージを受ける",
    desc: "",
    tags: ["セルフケア", "お出かけ"],
    satisfaction: 3,
    time: 3,
    price: 4,
  },
  {
    title: "好きな服を買う",
    desc: "",
    tags: ["買い物", "お出かけ"],
    satisfaction: 3,
    time: 3,
    price: 5,
  },
  {
    title: "ゲームの課金",
    desc: "500円分",
    tags: ["ゲーム", "買い物"],
    satisfaction: 2,
    time: 1,
    price: 2,
  },
  {
    title: "タピオカを飲む",
    desc: "",
    tags: ["食べ物", "お出かけ"],
    satisfaction: 1,
    time: 1,
    price: 2,
  },
  {
    title: "スイーツ巡りをする",
    desc: "",
    tags: ["食べ物", "お出かけ"],
    satisfaction: 3,
    time: 4,
    price: 3,
  },
  {
    title: "旅行の計画を立てる",
    desc: "",
    tags: ["まったり", "準備"],
    satisfaction: 2,
    time: 3,
    price: 1,
  },
  {
    title: "日帰り旅行",
    desc: "",
    tags: ["お出かけ", "外出"],
    satisfaction: 3,
    time: 6,
    price: 4,
  },
  {
    title: "好きな動画を倍速なしで見る",
    desc: "",
    tags: ["動画", "まったり"],
    satisfaction: 2,
    time: 3,
    price: 1,
  },
  {
    title: "ゆっくり料理する",
    desc: "好きなもの",
    tags: ["食べ物", "まったり"],
    satisfaction: 2,
    time: 3,
    price: 2,
  },
  {
    title: "パフェを食べる",
    desc: "",
    tags: ["食べ物", "お出かけ"],
    satisfaction: 3,
    time: 1,
    price: 2,
  },
  {
    title: "ゲームを思う存分する",
    desc: "3時間",
    tags: ["ゲーム"],
    satisfaction: 3,
    time: 5,
    price: 1,
  },
  {
    title: "サウナに行く",
    desc: "",
    tags: ["セルフケア", "お出かけ"],
    satisfaction: 3,
    time: 3,
    price: 3,
  },
  {
    title: "ネットサーフィンする",
    desc: "30分",
    tags: ["スマホ", "まったり"],
    satisfaction: 1,
    time: 2,
    price: 1,
  },
  {
    title: "好きな人と電話する",
    desc: "",
    tags: ["人間関係"],
    satisfaction: 3,
    time: 3,
    price: 1,
  },
];

async function main() {
  if (process.env.NODE_ENV === "production") {
    throw new Error(
      "シードスクリプトは本番環境では実行できません。NODE_ENV を確認してください。",
    );
  }

  // 既存のテストユーザーを削除してから再作成
  const TEST_USER_ID = "seed-test-user";

  await prisma.doneAction.deleteMany({ where: { userId: TEST_USER_ID } });
  await prisma.doneReward.deleteMany({ where: { userId: TEST_USER_ID } });
  await prisma.action.deleteMany({ where: { userId: TEST_USER_ID } });
  await prisma.reward.deleteMany({ where: { userId: TEST_USER_ID } });
  await prisma.user.deleteMany({ where: { id: TEST_USER_ID } });

  await prisma.user.create({
    data: {
      id: TEST_USER_ID,
      actions: { createMany: { data: DEFAULT_ACTIONS } },
      rewards: { createMany: { data: DEFAULT_REWARDS } },
    },
  });

  console.log(
    `✅ シード完了: ユーザー "${TEST_USER_ID}" にデフォルトデータを挿入しました`,
  );
  console.log(
    `   ブラウザのCookieに userId=${TEST_USER_ID} をセットして確認してください`,
  );
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(() => prisma.$disconnect());
